### ISSUE TITLE
Condo Documentation

### ISSUE THREAD

**Issue by dmccaffery** [pulsebridge/condo#3]
For now, I would like to get all of the shades supported by condo documented. 

For each of the macros, I would like the following details:
* name
* description
* supported operating systems
* arguments
* global arguments (those not prefixed with the name of the shade)
* related shades (see also)

The documentation markdown file should be named after the shade (excluding the _), and placed in the ```docs/shades``` path within the ```gh-pages``` branch.

``` md
---
layout: docs
title: Update self
group: shades
---

Updates the build scripts located at the root of the project structure.

## Contents
* Will be replaced with the ToC, excluding the "Contents" header
{:toc}

## Supported Operating Systems

{% icon fa-apple fa-3x %} {% icon fa-windows fa-3x %} {% icon fa-linux fa-3x %}

## Arguments

This uses no arguments.

## Global Arguments

The following global arguments are used by bower:

<div class="table-responsive">
    <table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th style="width:100px;">Name</th>
            <th style="width:50px;">Type</th>
            <th style="width:50px;">Default</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>base_path</td>
            <td>string</td>
            <td><code>$PWD</code></td>
            <td>The base path in which condo was executed.</td>
        </tr>
    </tbody>
    </table>
</div>

## Examples

Condo can update itself by adding the following call within any target:

{% highlight sh %}
    update-self
{% endhighlight %}

The default lifecycle includes a target aptly named `#update-self` that calls this shade.

## See Also

There are no related shades.
```

The following macros exist and need to be documented in the gh-pages branch:

- [x] bower
- [x] bower-download
- [x] bower-install
- [x] brew
- [x] brew-download
- [x] brew-install
- [x] bundle
- [x] bundle-download
- [x] bundle-install
- [x] dotnet-clean
- [x] copy
- [x] dotnet-cover
- [x] dotnet-cover-report
- [x] dnu
- [x] dotnet-build
- [x] dotnet-pack
- [x] dotnet-restore
- [x] dnu-locate
- [x] dnx
- [x] dotnet-run
- [x] dotnet-test
- [x] dotnet-watch
- [x] dnx-watch-download
- [x] exec
- [x] gem
- [x] gem-install
- [x] gem-locate
- [x] git
- [x] git-config
- [x] git-tag
- [x] gm-download
- [x] grunt
- [x] grunt-download
- [x] gulp
- [x] gulp-download
- [x] info
- [x] info-collect
- [x] log
- [x] mkdir
- [x] mocha
- [x] mocha-download
- [x] node
- [x] node-download
- [x] npm
- [x] npm-install
- [x] nuget
- [x] nuget-pack
- [x] nuget-push
- [x] nuget-restore
- [x] rimraf
- [x] rimfraf-download
- [x] ruby
- [x] ruby-locate
- [x] run
- [x] tsd
- [x] tsd-download
- [x] update-self
- [x] verify-hash

**Comment by itomek** [comment]
I don't see _tsd_install.shade :person_frowning:

**Comment by dmccaffery** [comment]
... I have no idea what you're talking about.

**Comment by itomek** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers:

**Comment by dmccaffery** [comment]
Uh.....

**Comment by itomek** [comment]
ok i could have SWORN that you had tsd-install in the list above... as well as tsd-download. So I figured you removed it after my comment and then added a sarcastic "... I have no idea what you're talking about." comment. Either way, it's no longer there.

**Comment by dmccaffery** [comment]
Hmm... It's magic. :)
