### ISSUE TITLE
running condo.sh on ubuntu gives dnvm-locate error

### ISSUE THREAD

**Issue by nithinsatheesh79** [pulsebridge/condo#8]
1. I have installed yo and condo-generator on ubuntu 14.04
2. when i run the condo script file i get 
 fail: dnvm-locate: could not find an instance of dnvm. The build process cannot continue, though there     are instances of dnvm.

**Comment by dmccaffery** [comment]
@nithinsatheesh79 Thank you for the feedback. We have only tested condo on OS X and Windows to date, but I am in the process of installing Ubuntu 14.04 into a virtual machine to try to reproduce the issue.

The dnvm-locate task does a little bit of magic to try to find the current version of dnvm.cmd (windows) or dnvm.sh (osx/linux) by searching the current PATH, followed by making an educated guess by looking for it at ~/.dnx/dnvm.

I'll keep digging and report my findings, but it might help to know a few things in the meantime:

1) Which version of dnvm are you currently running?
2) Is it installed in your local profile, or globally on the system?
3) if you run "which dnvm" and "which dnvm.sh", what path is emitted?

**Comment by dmccaffery** [comment]
I am able to reproduce this and will be working to resolve this as soon as possible. We do run a test build of condo on a linux environment in travis-ci, but we obviously need to figure out a way to do some more thorough testing on Ubuntu 14.04, since it is (supposedly) a supported platform for .NET 5.0.

<img width="1226" alt="ubuntu" src="https://cloud.githubusercontent.com/assets/1803684/12376964/5688049e-bcc1-11e5-87ad-e7a299d63e95.png">

**Comment by dmccaffery** [comment]
I have applied a hotfix that should resolve the issue.

Please do one of the following:

1) run condo to update-self:
```bash
./condo.sh update-self
```

2) delete the packages folder at the root of your project.

Condo should now execute successfully on Ubuntu 14.04.

If you have any more issues related to this bug, please feel free to re-open. Thanks, and good luck!

**Comment by nithinsatheesh79** [comment]
Hi Deavon,

Very nice to here from you. I will try to run it and i will get back to you
on the outcome at the earliest.


Thanks and Regards,
Nithin Satheesh.
